# Generated by Django 4.1.6 on 2023-03-29 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunities', '0003_customuser_is_ap_customuser_is_qa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_slotter',
            new_name='is_receiving',
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_slots', models.PositiveIntegerField(default=0)),
                ('total_slots', models.PositiveIntegerField(default=0)),
                ('job_functions', models.CharField(choices=[('Unloading', 'Unloading'), ('Loading', 'Loading'), ('Pallet Picking', 'Pallet Picking'), ('Reserve Picking', 'Reserve Picking'), ('Receiving', 'Receiving'), ('Yard Driving', 'Yard Driving'), ('Desk Clerking', 'Desk Clerking'), ('QA', 'QA'), ('Office Admin', 'Office Admin'), ('AP', 'AP')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
