# Generated by Django 4.1.6 on 2023-03-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunities', '0005_rename_is_receiving_customuser_is_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='total_slots',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='job_functions',
            field=models.CharField(blank=True, choices=[('Unloading', 'Unloading'), ('Loading', 'Loading'), ('Pallet Picking', 'Pallet Picking'), ('Reserve Picking', 'Reserve Picking'), ('Receiving', 'Receiving'), ('Yard Driving', 'Yard Driving'), ('Desk Clerking', 'Desk Clerking'), ('QA', 'QA'), ('Office Admin', 'Office Admin'), ('AP', 'AP')], max_length=255, null=True),
        ),
    ]
