# Generated by Django 4.1.6 on 2023-03-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunities', '0006_remove_opportunity_total_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='total_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='job_functions',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='job_functions',
            field=models.ManyToManyField(to='Opportunities.jobfunction'),
        ),
    ]
