# Generated by Django 4.1.6 on 2023-03-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunities', '0008_remove_opportunity_job_functions_delete_jobfunction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='end_time',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='start_time',
            field=models.CharField(max_length=7),
        ),
    ]
