# Generated by Django 4.1.6 on 2023-03-31 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunities', '0009_alter_opportunity_end_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opportunity',
            unique_together={('date', 'reserved_by')},
        ),
    ]
