# Generated by Django 4.1.6 on 2023-04-06 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunities', '0010_alter_opportunity_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opportunity',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='reserved_by',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='reserved_by',
            field=models.ManyToManyField(blank=True, related_name='opportunities_reserved', to=settings.AUTH_USER_MODEL),
        ),
    ]
