# Generated by Django 4.1.6 on 2023-04-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunities', '0011_alter_opportunity_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='reserved_by_names',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
