# Generated by Django 4.1.6 on 2023-04-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunities', '0012_opportunity_reserved_by_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='total_slots',
        ),
    ]
