# Generated by Django 4.1.6 on 2023-04-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunities', '0013_remove_opportunity_total_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='available_slots',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
